### ISSUE TITLE
CMake Opencv error 

### ISSUE THREAD

**Issue by evinpinar** [hanseuljun/temporal-rvl#1]
After I installed OpenCV with vcpkg, I try to cmake the cpp folders but receive this error: 
How can I solve this?

`CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!`

**Comment by hanseuljun** [comment]
The powershell script I built is only for Windows. Of course you can do it directly using cmake but don't forget to let cmake know where to look at (i.e., vcpkg) with setting DCMAKE_TOOLCHAIN_FILE. init-cmake.ps1 may function as an example for doing this...

**Comment by hanseuljun** [comment]
I just learned that you aren't using a Windows machine. Sorry but don't have access to a linux machine at this point and cannot help you more...
